### ISSUE TITLE
Reconnect after remote side closes a connection

### ISSUE THREAD

**Issue by rtborg** [rossmann-engineering/EEIP.NET#14]
Hello

I am experiencing the following issue: the remote device is power-cycled, I detect a timeout using `eeipClient.LastReceivedImplicitMessage`, and attempt to close the session using `ForwardClose()` and `UnRegisterSession()`. I receive an exception in `ForwardClose()`:
 `System.IO.IOException: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.`

Then I try to reconnect by creating a new instance of `eeipClient` object, and receive the following exception:
`Only one usage of each socket address (protocol/network address/port) is normally permitted`

Is there a way to properly determine if a connection has been dropped by the remote device, and reestablish it?

**Comment by rossmann-engineering** [comment]
I pushed a new version now which should close the Port even if the connection was closed by the Remote Device.
Your reconnection procedure should handle Exceptions properly if the Device connection is not available
