### ISSUE TITLE
Why Vendor ID and Serial Number are 0xFF?

### ISSUE THREAD

**Issue by MitSeven** [rossmann-engineering/EEIP.NET#27]
Hi
I'm still having trouble using Forwardopen ().
When I checked I saw Vendor ID and Serial Number item. Do I have to declare the same information in the EDS file?

**Comment by PimZTI** [comment]
Yes, that solved my issues with fanuc

**Comment by MitSeven** [comment]
Thanks for your response. I have fixed my problem. It turns out that my device provider does not support O_T_Instance ID which I have used
