### ISSUE TITLE
Getting compilation error while running example given for Explicit and Implicit message or any .cs file

### ISSUE THREAD

**Issue by rajatkmehta** [rossmann-engineering/EEIP.NET#4]
I have downloaded dll from sourceforge.net then decompiled it.
After that tried compile 'Program.cs' but getting compilation error.

error CS0246: The type or namespace name `Sres' could not be found. Are you missing an assembly reference?

Please guide me to run this program.

**Comment by IlliniHiker** [comment]
Download the whole EEIP.NET folder.  It has the whole Visual Studio project.

**Comment by rajatkmehta** [comment]
@IlliniHiker can any one has the same code written in Python? If not, then tell me how we can run this library can be run on linux ?

**Comment by IlliniHiker** [comment]
I don't know of any Python implementations.  You could convert this project to .NET Core and then it should run on Linux.

**Comment by rossmann-engineering** [comment]
Possibly the Java implementation is something you are looking for? You should be able run the Java implementation under linux.
Converting to .NET Core could be a solution, but not that easy, because we use some Namespaces which are not supported by .NET core.

**Comment by rajatkmehta** [comment]
@rossmann-engineering @IlliniHiker 
I have installed Mono on linux to run EEIP.NET codes but while running Program.cs (available in Implicit Example), getting thus as given below..
Program.cs(2,7): error CS0246: The type or namespace name `Sres' could not be found. Are you missing an assembly reference?
Compilation failed: 1 error(s), 0 warnings

Any idea why I am getting this on Mono, the same is working fine while running from visual studio on windows?

**Comment by rajatkmehta** [comment]
Is this Sres.Net.EEIP generic library of .Net Frame work, because I am getting issue while compling from MONO in linux. A simple hello.cs file is compiling using mono.

**Comment by rajatkmehta** [comment]
@rossmann-engineering 
In Java version of same library all CIP objects are not covered and there is no example for Implicit as well. But EEP.Net has covered every objects with both the Explicit/Implicit examples.

**Comment by rossmann-engineering** [comment]
The usage of Java and .NET Version is exactly the same

**Comment by rossmann-engineering** [comment]
http://eeip-library.de/codesamples-java/

**Comment by rajatkmehta** [comment]
@rossmann-engineering 
Only Assembly and Connection Manager objects are there, Identity Object, TCP/IP Object, Message Router Object are missing in java code.

Regarding "using Sres.Net.EEIP;" used in .NET: Is this a generic like "using System;"? Because A simple hello.cs file is compiling fine using mono in (linux).
using System; -->working fine
using Sres.Net.EEIP; -->not working in Mono (linux)
