### ISSUE TITLE
Can I make a modification for use in an application?

### ISSUE THREAD

**Issue by gkscloud** [rossmann-engineering/EEIP.NET#5]
Hi, 

This is a great library! Is it possible for me to use your implementation with a slight modification that is specific to my use case?  I am building a wrapper around your EEIP.dll for which I need to access the underlying TCP client network stream. My wrapper has a custom function that can read/write variables. If you prefer, I can submit a pull request with my changes?

GK.

**Comment by rossmann-engineering** [comment]
Hi, feel free to make any changes you want.
