### ISSUE TITLE
how to use Tag ?

### ISSUE THREAD

**Issue by yanzixiang** [rossmann-engineering/EEIP.NET#7]
I use [cpppo](https://github.com/pjkundert/cpppo)

A Tag is simply a shortcut to a specific EtherNet/IP CIP Object Instance and Attribute. Instead of the Client needing to know the specific Instance and Attribute numbers, the more easily remembered and meaningful Tag may be supplied in the request path.

how to use Tag in EEIP.NET?

**Comment by rossmann-engineering** [comment]
Hi,

the library is simply a tool to access Ethernet/IP Devices. To map any Requests to a Tag, would be something you have to build yourself.
